In [ ]:
import pandas as pd
import numpy as np
from lets_plot import *
LetsPlot.setup_html()
# Review of Python Dictionaries
# Empty dictionary
items = {}
values = dict()

print(items, type(items))
print(values, type(values))
# Creating a Dict with some key, value pairs
students = {
    'Bob': '123-12-1234',
    'Mary': '324-54-6375',
    'Jim': '809-76-7745'
}

students
# Using a Dict

print(students)

print(students['Bob'])
print(students['Mary'])
print(students['Jim'])
# Adding to a Dict

print(students)

students['Alice'] = '999-99-9999'

print(students)
# Pandas example

df = pd.read_csv('iris.csv')
df
# adding a new columns
df['new_column'] = 0
df
rows = df.shape[0]
df['count'] = range(rows)
df
# duplicate a row
df['sepallen'] = df['SepalLengthCm']
df
# duplicate a column and multiple all values by 100
df['sepallen100'] = df['SepalLengthCm'] * 100
df
# Data Frame of MPG
df = pd.read_csv('mpg.csv')
df
# TODO - Create a new column named "average" that is the average of cty and hwy values

# TODO - rename "midsize" in the class column to "mid"

# TODO - What is a average hwy mileage for volkswagens

# TODO - What is a average cty mileage for all a4 cars